---
title: ""
always_allow_html: yes
output:
  html_document:
    keep_md: true
    toc: true
    theme: simplex
---

```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  include = FALSE,
  # fig.show = "hide"
  fig.align = "center"
)
```

```{r packages}
library("teplot")
invisible(source(".Rprofile"))
```


```{r import}
rapm_estimates <- .try_import_rapm_estimates()
rapm_basektball_analytics <- .try_import_rapm_basketballanalytics()
rpm_espn <- .try_import_rpm_espn()
```

```{r rgx_src}
src_order <- c("calc", "basketballanalytics", "espn")
src_order_debug <- c(src_order, "nbastatr")
.create_rgx <-
  function(x) {
    paste0("(", paste(x, collapse = ")|(", sep = ""), ")") %>%
      str_replace_all("\\.", "[.]")
  }
rgx_src <- src_order %>% .create_rgx()
rgx_src_debug <- src_order_debug %>% .create_rgx()
```


```{r rapm_estimate_slim}
rapm_estimates_slim <-
  rapm_estimates %>%
  select(-matches("[o|d]rapm_rank")) %>%
  rename_at(vars(matches("rank|rapm")), funs(paste0(., "_calc"))) %>%
  select(
    season,
    name,
    matches("rank|rapm")
  )
```

# My Estimates

```{r rapm_estimates_slim_show_prep1}
# library("data.table")
# getOption("datatable.print.topn")
# getOption("datatable.print.nrows")
# getOption("datatable.print.rownames")
# options(datatable.print.topn = 10, datatable.print.rownames = FALSE, max.print = 200)
rapm_estimates_slim_show <-
  rapm_estimates_slim %>%
  rename_at(vars(matches("_calc$")), funs(str_remove(., "_calc$"))) %>% 
  mutate(grp = season) %>% 
  group_by(grp) %>% 
  nest() %>% 
  mutate(data = purrr::map(data, data.table::as.data.table)) %>% 
  mutate(dummy = purrr::walk(data, ~data.table:::print.data.table(x = .x)))
```

```{r rapm_estimates_slim_show1, include = TRUE}
rapm_estimates_slim_show
```

```{r rapm_estimates_slim_show_prep2}
rapm_estimates_slim_show <-
  rapm_estimates_slim %>%
  rename_at(vars(matches("_calc$")), funs(str_remove(., "_calc$"))) %>% 
  group_by(season) %>% 
  arrange(rank) %>% 
  slice(1:10) %>% 
  ungroup() %>% 
  arrange(desc(season), rank) %>% 
  mutate_if(is.double, funs(round(., 2))) %>% 
  knitr::kable(output_format = "markdown")
```

```{r rapm_estimates_slim_show2, include = TRUE}
rapm_estimates_slim_show
```

Check against: https://public.tableau.com/views/14YearRAPM/14YearRAPM?%3Aembed=y&%3AshowVizHome=no

```{r viz_rapm_estimates}
viz_rapm_estimates <-
  rapm_estimates_slim %>% 
  ggplot(aes(x = orapm_calc, y = drapm_calc)) +
  geom_hline(aes(yintercept = 0)) +
  geom_vline(aes(xintercept = 0)) +
  geom_point(aes(size = rapm_calc, color = rapm_calc)) +
  # geom_hex() +
  # scale_fill_viridis_c(option = "E")
  scale_color_distiller(palette = "RdYlBu", direction = 1) +
  # scale_color_gradient2(low = "red", high = "blue")
  teplot::theme_te() +
  guides(color = FALSE, size = FALSE) +
  theme(
    legend.position = "right"
  ) +
  labs(
    title = "Calculated Single-Season, Traditional RAPM",
    subtitle = "2015 - 2017 NBA Seasons",
    caption = "By Tony ElHabr",
    x = "ORAPM",
    y = "DRAPM"
  )
viz_rapm_estimates
```

```{r viz_rapm_estimates_export, eval = FALSE}
teproj::export_ext_png(
  viz_rapm_estimates,
  dir = "figs",
  units = "in",
  height = 7,
  width = 7
)
```

```{r viz_rapm_estimates_show, include = TRUE, fig.show = "asis"}
viz_rapm_estimates
```


# Comparisons

```{r estimates_compare}
rapm_basektball_analytics_slim <-
  rapm_basektball_analytics %>% 
  rename_at(vars(matches("rank|rapm")), funs(paste0(., "_basketballanalytics"))) %>%
  select(
    season,
    name,
    slug,
    matches("rank|rapm")
  )
rpm_espn_slim <-
  rpm_espn %>%
  rename_at(vars(matches("rank|rpm")), funs(paste0(., "_espn"))) %>%
  select(
    season,
    name,
    position,
    matches("rank|rpm")
  )

estimates_compare <-
  rapm_estimates_slim %>% 
  left_join(rapm_basektball_analytics_slim, by = c("season", "name")) %>%
  left_join( rpm_espn_slim, by = c("season", "name")) %>%
  select(
    season,
    name,
    slug,
    matches("rank"),
    matches("^r"),
    matches("^o"),
    matches("^d")
  )
estimates_compare
```

## With basketball-analytics

```{r estimates_compare_basketballanalytics}
estimates_compare
```


## With ESPN


## Cause(s) for Differences?

```{r import_players_summary_compare}
players_summary_compare <- .try_import_players_summary_compare()
```

```{r estimates_compare_debug}
estimates_compare_debug <-
  estimates_compare %>% 
  left_join(
    players_summary_compare %>% 
      rename(id = id_player, name = name_player),
    by = c("season", "name")
  ) %>% 
  rename(mp_calc = mp_calc_total) %>% 
  mutate(
    rapm_basketballanalytics_diff = rapm_calc - rapm_basketballanalytics,
    orapm_basketballanalytics_diff = orapm_calc - orapm_basketballanalytics,
    drapm_basketballanalytics_diff = drapm_calc - drapm_basketballanalytics,
    # rank_basketballanalytics_diff = rank_calc - rank_basketballanalytics,
    # gp_diff = gp_calc_total - gp_summary_nbastatr,
    mp_diff = mp_calc - mp_game_logs_nbastatr,
    pm_diff = pm_calc - pm_game_logs_nbastatr
  )

estimates_compare_debug_slim <-
  estimates_compare_debug %>% 
  mutate(
    mp_diff_rate = mp_diff / mp_calc,
    pm_diff_rate = pm_diff / pm_calc
  ) %>% 
  mutate_if(is.double, funs(if_else(is.infinite(.), 0, .))) %>% 
  select(
    season,
    # matches("^(gp|mp|pm).*calc"),
    # matches("diff")
    matches("^(mp|pm)_calc$"),
    matches("_diff$"),
    matches("_rate$")
  )
estimates_compare_debug_slim
```

```{r viz_estimates_compare_debug, eval = FALSE}
estimates_compare_debug_slim_tidy <-
  estimates_compare_debug_slim %>% 
  select_at(vars(matches("^(mp|pm).*(calc|diff)$"))) %>% 
  gather(calc_metric, calc_value, matches("_calc$")) %>% 
  gather(diff_metric, diff_value, matches("_diff$")) %>% 
  mutate(prefix = calc_metric %>% str_remove("_.*$"))
viz_estimates_compare_debug_slim_tidy1 <-
  estimates_compare_debug_slim_tidy %>% 
  ggplot(aes(x = calc_value, y = diff_value, color = prefix)) +
  geom_point(alpha = 0.1) +
  facet_wrap(~prefix, scales = "free")
viz_estimates_compare_debug_slim_tidy1
viz_estimates_compare_debug_slim_tidy2 <-
  estimates_compare_debug_slim_tidy %>% 
  ggplot(aes(x = diff_value, fill = prefix)) +
  # geom_histogram(bins = 50) +
  geom_density(alpha = 0.8) +
  # scale_y_continuous(labels = scales::percent) +
  facet_wrap(~prefix, scales = "free")
viz_estimates_compare_debug_slim_tidy2
```


```{r fit_estimates_compare_debug, eval = FALSE}
fmlas_lhs <-  paste0(c("o", "d"), "rapm_basketballanalytics_diff")
nms_rhs <-
  estimates_compare_debug_slim %>% 
  names() %>% 
  str_subset("^(mp|pm).*(calc|diff|rate)$")

`%do%` <- foreach::`%do%`
combs_rhs <- 
  foreach::foreach(i = 1:length(nms_rhs), .combine=c) %do% {combn(nms_rhs, i, simplify = FALSE) }
fmlas_rhs <-
  combs_rhs %>% 
  purrr::map_chr(~paste0(.x, collapse = " + ", sep = ""))
fmlas_rhs
grid_fmlas <-
  crossing(
    y = fmlas_lhs,
    x = fmlas_rhs
  )
grid_fmla
fmla_rhs <-
  estimates_compare_debug_slim %>% 
  names() %>% 
  # str_subset("^(mp|pm)_(calc|diff|rate)$") %>% 
  # str_subset("^(mp|pm)_(diff_rate)$") %>%
  str_subset("^(mp|pm)_(diff)$") %>%
  paste(collapse = " + ", sep = "")
fits_estimates_compare_debug <-
  grid_fmlas %>% 
  group_by(y) %>% 
  mutate(fit = 
           purrr::pmap(list(y, x), 
                       ~lm(formula = formula(paste0(..1, " ~ ", ..2)), 
                           data = estimates_compare_debug_slim)
           )
  ) %>%
  mutate(estimates = purrr::map(fit, broom::tidy)) %>% 
  ungroup() %>% 
  select(y, x, estimates) %>% 
  unnest(estimates) %>% 
  arrange(y, x, p.value)
fits_estimates_compare_debug

fits_estimates_compare_debug_filt1 <-
  fits_estimates_compare_debug %>%
  filter(x == "mp_diff + pm_diff")
fits_estimates_compare_debug_filt1

fits_estimates_compare_debug_filt1 <-
  fits_estimates_compare_debug %>%
  filter(x == "mp_diff_rate + pm_diff_rate")
fits_estimates_compare_debug_filt1

```

```{r estimates_compare_slim, eval = FALSE}
estimates_compare_slim <-
  estimates_compare %>%
  select(
    season,
    name,
    slug,
    matches("rank"),
    matches("^ra?pm")
  )

estimates_compare_slim1 <-
  estimates_compare_slim %>%
  select(-matches("espn"))

estimates_compare_slim1 %>%
  print(n = 25)
estimates_compare_slim2 <-
  estimates_compare_slim %>%
  select(-matches("basketballanalytics"))

estimates_compare_slim
estimates_compare_slim %>%
  mutate(diff = (rank_calc - rank_basketballanalytics)) %>%
  arrange(abs(diff))

estimates_tidy <-
  estimates_compare %>%
  gather(metric_src, value, matches(rgx_src)) %>%
  separate(metric_src, into = c("metric", "src"), sep = "_") %>%
  mutate_at(vars(src), funs(factor(., levels = src_order)))
estimates_tidy
estimates_tidy %>% pull(src) %>% levels()

estimates_h2h <-
  estimates_tidy %>%
  filter(metric == "rank") %>%
  spread(src, value) %>%
  select(-metric) %>%
  arrange(season, calc)
estimates_h2h

estimates_norm <-
  estimates_tidy %>%
  group_by(season, src, metric) %>%
  mutate_at(vars(value), funs(value_prank = dplyr::percent_rank(-.))) %>%
  ungroup()
estimates_norm

estimates_cors <-
  estimates_tidy %>%
  # estimates_norm %>%
  filter(metric == "rank") %>%
  spread(src, value) %>%
  group_by(season) %>%
  nest() %>%
  mutate(cors =
           purrr::map(data,
                      ~select_at(.x, vars(matches(rgx_src))) %>%
                        corrr::correlate(method = "spearman")
           )
  ) %>%
  ungroup() %>%
  unnest(cors) %>%
  gather(src2, value, matches(rgx_src)) %>%
  rename(src1 = rowname) %>%
  arrange(season, src1, src2) %>%
  filter(!is.na(value)) %>%
  filter(src1 < src2)
estimates_cors

estimates_norm_viz <-
  estimates_norm %>%
  filter(metric == "rank") %>%
  spread(src, value) %>%
  # filter(espn > 0.75 | calc > 0.75) %>%
  mutate(diff = espn - calc) %>%
  mutate(
    diff_grp = diff %>% abs() %>% ggplot2::cut_width(0.25)
  )
estimates_norm_viz <-
  estimates_norm_viz %>%
  left_join(
    estimates_norm_viz %>%
      filter(!is.na(diff)) %>%
      group_by(diff_grp) %>%
      sample_frac(0.05) %>%
      ungroup() %>%
      mutate(name_diff = name)
  )
estimates_norm_viz
viz_estimates_norm1 <-
  estimates_norm_viz %>%
  filter(espn > 0.75 | calc > 0.75) %>%
  ggplot(aes(x = espn, y = calc, color = diff_grp)) +
  geom_point() +
  ggrepel::geom_label_repel(
    aes(label = name_diff)
  ) +
  teplot::theme_te()
viz_estimates_norm1

viz_estimates_norm2 <-
  estimates_norm_viz %>%
  # filter(espn > 0.75 | calc > 0.75) %>%
  ggplot(aes(x = diff, fill = diff_grp)) +
  geom_histogram() +
  teplot::theme_te()
viz_estimates_norm2
```

